name: CI

on:
  [push]
jobs:
  push_to_registry:
    name: push to registry
    runs-on: ubuntu-latest
    steps:
      - name: firstStep
        uses: actions/checkout@v4

      - name: secondStep
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/sagr0m/py:1.0 ./1
      - run: docker push ghcr.io/sagr0m/py:1.0
      - run: docker build -t ghcr.io/sagr0m/js:1.0 ./2
      - run: docker push ghcr.io/sagr0m/js:1.0
  docker_run:
    needs: [push_to_registry]
    name: docker_run
    runs-on: ubuntu-latest
    steps:
      - name: firstStep
        uses: actions/checkout@v4

      - name: secondStep
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull ghcr.io/sagr0m/py:1.0
      - run: docker run ghcr.io/sagr0m/py:1.0
      - run: docker pull ghcr.io/sagr0m/js:1.0
      - run: docker run ghcr.io/sagr0m/js:1.0
